// This file was generated by FMOD for Unity from the Static Plugins list in the FMOD settings.

using System;
using System.Runtime.InteropServices;

namespace FMODUnity
{
    class StaticPluginManager
    {
        [DllImport(FMOD.VERSION.dll)]
        private static extern FMOD.RESULT FMOD5_System_RegisterDSP(IntPtr system, IntPtr description, IntPtr handle);

        public static void Register(FMOD.System coreSystem, Action<FMOD.RESULT, string> reportResult)
        {
        }
    }
}
